version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        command: "npm run dev"
        ports:
            - "5000:3000"
        volumes:
            - "${PWD}/:/app"
    database:
        image: mongo:4.4.6
        ports:
            - "27017:27017"
        volumes: 
            - "${PWD}/.docker/mongo:/data/db"
